force-app/main/default/objects/Drive__e/Drive__e.object-meta.xml
<CustomObject>
    <label>Drive</label>
    <pluralLabel>Drives</pluralLabel>
    <description>drives associated with a vehicle</description>
</CustomObject>

force-app/main/default/objects/Drive__e/fields/Ending_Odometer__c.field-meta.xml
<CustomField>
    <label>Ending Odometer</label>
    <type>Number</type>
    <fullName>Ending_Odometer__c</fullName>
    <scale>1</scale>
    <precision>17</precision>
</CustomField>

force-app/main/default/objects/Drive__e/fields/VIN__c.field-meta.xml
<CustomField>
    <label>VIN</label>
    <type>Text</type>
    <fullName>VIN__c</fullName>
    <length>17</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Scheduled_Maintenance__c/Scheduled_Maintenance__c.object-meta.xml
<CustomObject>
    <label>Scheduled Maintenance</label>
    <pluralLabel>Scheduled Maintenance</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>SM-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not scheduled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Scheduled Maintenance</relationshipLabel>
    <relationshipName>Scheduled_Maintenance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Scheduled_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Maintenance</label>
    <referenceTo>Scheduled_Maintenance__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dataReset.cls
public with sharing class dataReset {

    @AuraEnabled
    public static void dataReset1() {
        Vehicle__c v = [select id, Vin__c, Scheduled_Maintenance__c from Vehicle__c where Vin__c = 'YV1DZ8256C2271234'];

        // move vehicle maint to Scheduled
        Scheduled_Maintenance__c SM = [select id, Status__c from Scheduled_Maintenance__c where id =: v.Scheduled_Maintenance__c];
        SM.Status__c = 'Scheduled';
        update SM;

    }

    @AuraEnabled
    public static void dataReset2() {
        Vehicle__c v = [select id, Vin__c, Scheduled_Maintenance__c from Vehicle__c where Vin__c = 'YV1DZ8256C2271234'];

        Drive__e d1 = new Drive__e();
        d1.Vin__c = v.Vin__c;
        d1.Ending_Odometer__c = 9995;
        Eventbus.publish(d1);

    }

    @AuraEnabled
    public static void dataReset3() {
        Vehicle__c v = [select id, Vin__c, Scheduled_Maintenance__c from Vehicle__c where Vin__c = 'YV1DZ8256C2271234'];
        Scheduled_Maintenance__c SM = [select id, Status__c from Scheduled_Maintenance__c where id =: v.Scheduled_Maintenance__c];

        SM.Status__c = 'Completed';
        update SM;

        // drop event
        Drive__e d2 = new Drive__e();
        d2.Vin__c = v.Vin__c;
        d2.Ending_Odometer__c = 200;
        Eventbus.publish(d2);

    }

    @AuraEnabled
    public static void dataReset4() {
        Vehicle__c v = [select id, Vin__c, Scheduled_Maintenance__c from Vehicle__c where Vin__c = 'YV1DZ8256C2271234'];

        Scheduled_Maintenance__c SM = [select id, Status__c from Scheduled_Maintenance__c where id =: v.Scheduled_Maintenance__c];

        SM.Status__c = 'Not scheduled';
        update SM;
    }

    public static void ResyncWithHeroku(){
        mutliplexSelfReg.reg();
    }


}