force-app/main/default/objects/Scheduled_Maintenance__c/Scheduled_Maintenance__c.object-meta.xml
<CustomObject>
    <label>Scheduled Maintenance</label>
    <pluralLabel>Scheduled Maintenance</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>SM-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not scheduled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Target_Date__c.field-meta.xml
<CustomField>
    <label>Target Date</label>
    <type>Date</type>
    <fullName>Target_Date__c</fullName>
</CustomField>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Target_Mileage__c.field-meta.xml
<CustomField>
    <label>Target Mileage</label>
    <type>Number</type>
    <fullName>Target_Mileage__c</fullName>
    <scale>0</scale>
    <precision>18</precision>
</CustomField>

force-app/main/default/objects/Scheduled_Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Scheduled Maintenance</relationshipLabel>
    <relationshipName>Scheduled_Maintenance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Scheduled_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Maintenance</label>
    <referenceTo>Scheduled_Maintenance__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dataSetup.cls
public with sharing class dataSetup {

    public static void go() {
        Vehicle__c v = [select id, Scheduled_Maintenance__c from Vehicle__c where Vin__c = 'YV1DZ8256C2271234'];

        list<Scheduled_Maintenance__c> SMs = new list<Scheduled_Maintenance__c>();

        Scheduled_Maintenance__c SM = new Scheduled_Maintenance__c();
        SM.Target_Date__c = system.today().addDays(90);
        SM.Target_Mileage__c = 10000;
        SM.Vehicle__c = v.id;
        SM.Status__c = 'Not scheduled';
        SMs.add(SM);

        Scheduled_Maintenance__c SM2 = new Scheduled_Maintenance__c();
        SM2.Target_Date__c = system.today().addDays(180+90);
        SM2.Target_Mileage__c = 20000;
        SM2.Vehicle__c = v.id;
        SM2.Status__c = 'Not scheduled';
        SMs.add(SM2);

        Scheduled_Maintenance__c SM3 = new Scheduled_Maintenance__c();
        SM3.Target_Date__c = system.today().addDays(360+90);
        SM3.Target_Mileage__c = 30000;
        SM3.Vehicle__c = v.id;
        SM3.Status__c = 'Not scheduled';
        SMs.add(SM3);

        insert SMs;

        v.Scheduled_Maintenance__c = SM.Id;
        update v;


    }

}